name: Python Package using Conda

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.2'
    
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        conda env update --file environment.yaml
        conda install flake8
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # TODO: conside the latest release, not a hardcoded one!
    - name: Get reference results
      run: |
        curl -L -o pytest-results.zip "https://github.com/ifpen/bemol/releases/download/v0.0.1/pytest-results.zip"
        unzip pytest-results.zip
        mv tests/results tests/ref/

    - name: Test with pytest
      run: |
        source activate bemol
        pytest tests/ -vvs --reference tests/ref/
    